server:
  port: 8088
  servlet:
    context-path: /itsc


langchain4j:
  open-ai:
    #非流式对话模型
    chat-model:
      api-key: sk-ws-H.PIRLYYH.JPuT.MEUCIQDHb9mXx_Wgp51sbDlNYHkbEcC5tvvj4rf04ZkWpeu4gwIgZrJqfZFtIsri91swwVj16yYY8id-JTc0ov6Fb8d_AgY
      model-name: qwen3.8-flash
      bean-name: openAiChatModel
      base-url: https://ws-g32z8buv16crgc1y.cn-beijing.maas.aliyuncs.com/compatible-mode/v1
      log-requests: true                   # 建议开启，方便调试
      log-responses: true
      temperature: 0.7
      timeout: PT60S
    #文本转向量模型
    embedding-model:
      api-key: sk-ws-H.PIRLYYH.dO62.MEUCIQDHwiWVNxKlceqO74DNMOBMzu_LKykqOy2laGhkhLaKMwIgUjKkOmDthbx_e24VXmJuMIZ1g_9ydW2Cw5Z4-_qLhJ0
      model-name: text-embedding-v3
      base-url: https://ws-g32z8buv16crgc1y.cn-beijing.maas.aliyuncs.com/compatible-mode/v1
      bean-name: openAiEmbeddingModel
      log-requests: true
      log-responses: true
      timeout: PT60S
    # 流式对话模型
    streaming-chat-model: # ← 新增
      base-url: https://ws-g32z8buv16crgc1y.cn-beijing.maas.aliyuncs.com/compatible-mode/v1
      api-key: sk-ws-H.PIRLYYH.JPuT.MEUCIQDHb9mXx_Wgp51sbDlNYHkbEcC5tvvj4rf04ZkWpeu4gwIgZrJqfZFtIsri91swwVj16yYY8id-JTc0ov6Fb8d_AgY
      model-name: qwen3.8-flash
      temperature: 0.7
      timeout: PT60S
      log-requests: true
      log-responses: true

#      sk-ws-H.PIYYERR.1Nwn.MEUCIElKdWigzoNh0Q0oyc4diloh1kPaG985KNHutJFYZ_BcAiEAxSEiKGkUToaPuDQXxyTjjvFHlw-ijplt7phf64Nt6EM
#       https://ws-h0yse1g5h37z1f9s.cn-beijing.maas.aliyuncs.com/compatible-mode/v1