CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE IF NOT EXISTS na_sensitive_access_alert (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 10000) PRIMARY KEY,
    cmdb_id             varchar(255) NOT NULL,
    app_name            varchar(500),
    user_it_code        citext       NOT NULL,
    user_id             varchar(500),
    user_coc_type       varchar(20)  NOT NULL,
    system_role_id      text,
    system_role         text NOT NULL,
    role_description    text,
    role_classification varchar(50)  NOT NULL,
    alert_status        varchar(20)  NOT NULL DEFAULT 'Pending',
    alert_trigger_time  timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_time       timestamp,
    suppressed_by       varchar(255),
    suppressed_time     timestamp,
    suppressed_reason   varchar(2000),
    suppressed_requested_by varchar(255),
    last_send_time      timestamp,
    create_by           varchar(255) NOT NULL DEFAULT 'SYSTEM',
    create_time         timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by           varchar(255),
    update_time         timestamp,
    CONSTRAINT chk_na_sensitive_access_alert_status
        CHECK (alert_status IN ('Pending', 'Resolved', 'Suppressed')),
    CONSTRAINT chk_na_sensitive_access_alert_coc
        CHECK (UPPER(TRIM(user_coc_type)) = 'Y'),
    CONSTRAINT chk_na_sensitive_access_alert_role_classification
        CHECK (LOWER(TRIM(role_classification)) = 'sensitive'),
    CONSTRAINT chk_na_sensitive_access_alert_suppressed
        CHECK (
            alert_status != 'Suppressed'
            OR (suppressed_by IS NOT NULL AND suppressed_time IS NOT NULL AND NULLIF(TRIM(suppressed_reason), '') IS NOT NULL)
        )
);

COMMENT ON TABLE na_sensitive_access_alert IS
    '为担任NA敏感角色的CoC用户提供每日警报';
COMMENT ON COLUMN na_sensitive_access_alert.id IS '告警ID，自增序列从10000开始';
COMMENT ON COLUMN na_sensitive_access_alert.alert_trigger_time IS
    '此违规事件的首次检测时间';
COMMENT ON COLUMN na_sensitive_access_alert.resolved_time IS
    '每日扫描确认违规行为不再存在的时间';
COMMENT ON COLUMN na_sensitive_access_alert.suppressed_time IS
    '抑制此业务数据的时间';
COMMENT ON COLUMN na_sensitive_access_alert.suppressed_requested_by IS
    '告警抑制申请人';

CREATE UNIQUE INDEX IF NOT EXISTS uq_na_sensitive_access_alert_active
    ON na_sensitive_access_alert (
        cmdb_id,
        user_it_code,
        COALESCE(user_id, ''),
        COALESCE(system_role_id, ''),
        system_role
    )
    WHERE alert_status IN ('Pending', 'Suppressed');

CREATE INDEX IF NOT EXISTS idx_na_sensitive_access_alert_list
    ON na_sensitive_access_alert (alert_status, alert_trigger_time DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_iaad_na_sensitive_alert_source
    ON its_application_access_data (LOWER(user_it_code), cmdb_id)
    WHERE LOWER(TRIM(access_label)) = 'sensitive';

CREATE INDEX IF NOT EXISTS idx_upp_na_sensitive_alert_user
    ON ad_tb_upp_nature_2 (LOWER(user_name))
    WHERE UPPER(TRIM(coc_flag)) = 'Y';
